backend:
  name: github
  repo: 808raya/rayaleephotography
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "galleries"
    label: "Galleries"
    folder: "galleries"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Images", name: "images", widget: "image", multiple: true }
